version: '3'

services:
  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  gql:
    image: hasura/graphql-engine:v2.7.0
    ports:
      - 15003:8080
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
    depends_on:
      - db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis-ui:
    container_name: redis-ui
    image: redislabs/redisinsight:latest
    restart: always
    volumes:
      - redisinsight:/db 
    ports:
      - 8088:8001

volumes:
  pgdata:
  redisinsight:
    driver: local 